google_analytics: G-L0BXR0ZGW7
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
exclude: [lib/,examples/,test/,.gitignore,.npmignore,index.mjs,LICENSE,package.json,.github/,package-lock.json,_config.yml]